### ISSUE TITLE
about datasets

### ISSUE THREAD

**Issue by xzydxh** [baireuther/neural_network_decoder#1]
Hello, first of all, thank you very much for sharing the code. There are several questions I would like to ask you:
I generated the dataset for suface17 using your circut_model file, but with the data_format.md in your neural_network_decoder data fields are inconsistent.I modified the field names in the generated dataset, but I still can't train normally. How do you generate a dataset that meets the format requirements through the circuit_model file? Thank you very much.

**Comment by baireuther** [comment]
Dear xzydxh,

The code in this repository (neural_network_decoder) is not licensed for (re)use. It is only on display here so that the scientific community can see the details of the implementation.
